In [1]:
#Numpy 教程
import numpy as np #为了方便使用numpy 采用np简写
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)
print('number of dim:',array.ndim)  # 维度
print('shape :',array.shape)    # 行数和列数
print('size:',array.size)   # 元素个数

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape : (2, 3)
size: 6


In [9]:
#创建数组
a = np.array([2,23,4])  # list 1d
print(a)
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)
#创建特定数据
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)
a = np.zeros((3,4)) # 数据全为0，3行4列
a = np.empty((3,4)) # 数据为empty，3行4列
a = np.arange(10,20,2) # 10-19 的数据，2步长
#使用 reshape 改变数据的形状
a = np.arange(12).reshape((3,4))    # 3行4列，0到11  使用 reshape 改变数据的形状
print(a)
#用 linspace 创建线段型数据
a = np.linspace(1,20,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
print(a)

[ 2 23  4]
int32
[[ 2 23  4]
 [ 2 32  4]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.]


In [11]:
# numpy 的几种基本运算 1
a = np.array([10,20,30,40])   # array([10, 20, 30, 40])
b = np.arange(4)              # array([0, 1, 2, 3])
c = a - b
c = a + b
c = a * b
print(b < 3)

a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)
c_dot = np.dot(a,b)
c_dot_2 = a.dot(b)

print("b = \n",b)
print("sum =",np.sum(b,axis=1))
print("min =",np.min(b,axis=0))
print("max =",np.max(b,axis=1))

[ True  True  True False]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
b = 
 [[0 1]
 [2 3]]
sum = [1 5]
min = [0 1]
max = [1 3]


In [4]:
# numpy 的几种基本运算 1
A = np.arange(2,14).reshape((3,4)) 
print(A)
print(np.argmin(A))    # 0
print(np.argmax(A))    # 11
print(np.mean(A))        # 7.5
print(np.cumsum(A)) 
print(np.nonzero(A))  
# 返回非零元素的目录。
# 返回值为元组， 两个值分别为两个维度， 包含了相应维度上非零元素的目录值。   
# 可以通过a[nonzero(a)]来获得所有非零值。
print(np.clip(A,5,9))    
# 这个函数的格式是clip(Array,Array_min,Array_max)，顾名思义，Array指的是将要被执行用的矩阵，
#而后面的最小值最大值则用于让函数判断矩阵中元素是否有比最小值小的或者比最大值大的元素，并将这些指定的元素转换为最小值或者最大值。

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [5]:
#Numpy 索引
import numpy as np
A = np.arange(3,15)        
print(A[3])    # 6
A = np.arange(3,15).reshape((3,4))      
print(A[2])         
print(A[1, 1:3])    # [8 9]

6
[11 12 13 14]
[8 9]


In [12]:
#Numpy array 合并
A = np.array([1,1,1])
B = np.array([2,2,2])   
C = np.vstack((A,B))       # vertical stack 纵向合并
print(C)
D = np.hstack((A,B))       # horizontal stack　横向合并
print(D)

print(A[np.newaxis,:])
# [[1 1 1]]
print(A[np.newaxis,:].shape)
# (1,3)
print(A[:,np.newaxis])
print(A[:,np.newaxis].shape)
# (3,1)

#np.newaxis()
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
         
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack
print(C.shape,D.shape)
# (6,1) (3,2)
# 当你的合并操作需要针对多个矩阵或序列时，借助concatenate函数可能会让你使用起来比前述的函数更加方便：
C = np.concatenate((A,B,B,A),axis=0)
print(C)

D = np.concatenate((A,B,B,A),axis=1)
print(D)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)
(6, 1) (3, 2)
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [7]:
#Numpy array 分割
A = np.arange(12).reshape((3, 4))
print(A)
# 纵向分割 
print(np.split(A, 2, axis=1))
# 横向分割 
print(np.split(A, 3, axis=0))
# 不等量的分割 
#在机器学习时经常会需要将数据做不等量的分割，因此解决办法为np.array_split()
print(np.array_split(A, 3, axis=1))

#在Numpy里还有np.vsplit()与横np.hsplit()方式可用。
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))
print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [8]:
#Numpy copy & deep copy
# = 的赋值方式会带有关联性
a = np.arange(4)
b = a
c = a
d = b
# 改变a的第一个值，b、c、d的第一个值也会同时改变。
a[0] = 11
print(a)
# array([11,  1,  2,  3])
# 确认b、c、d是否与a相同。
print(b is a)  # True
print(c is a)  # True
print(d is a)  # True
#同样更改d的值，a、b、c也会改变。
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])

# copy() 的赋值方式没有关联性 
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11  1  2  3]
True
True
True
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
